#deployer is address of the contract deployer (who often is privileged owner, etc.)
deployer: "0x30000"

#sender is set of addresses transactions may originate from
sender: ["0x10000", "0x20000"]

#contractAddr is the address of the contract itself
contractAddr: "0x1234"

#whether ot not to use the multi-abi mode of testing
multi-abi: true  # allow the echidna to call function from other contracts
